title: Chang Kam Wa's Homepage
page-top-title: Chang Kam Wa
top-section-bg-text: Computer Science
home-subtitle: Chang Kam Wa&ensp;|&ensp;曾錦華
copyright-text: '&copy; Chang Kam Wa 2025-2026. All Rights Reserved.'
